language: python
dist: xenial
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
install:
  - pip install -e .[dev]
script:
  - pytest
